# 👉🏻 Default Rules
#    비활성시킬 Rules을 나열합니다. 주석처리된 Rule들이 활성되어있는 Rule입니다.
#    활성된(주석처리된) Rule 중 AutoCorrection이 되는 Rule은 `⭕️`를 추가해 구분했습니다.
disabled_rules:
  - block_based_kvo
  - class_delegate_protocol
  # - closing_brace ⭕️
  # - closure_parameter_position
  # - comma ⭕️
  # - comma_inheritance ⭕️
  # - comment_spacing ⭕️
  # - compiler_protocol_init
  - computed_accessors_order
  # - control_statement ⭕️
  # - custom_rules
  - cyclomatic_complexity
  - deployment_target
  # - discouraged_direct_init
  # - duplicate_enum_cases
  # - duplicate_imports
  # - duplicated_key_in_dictionary_literal
  # - dynamic_inline
  # - empty_enum_arguments ⭕️
  # - empty_parameters ⭕️
  # - empty_parentheses_with_trailing_closure ⭕️
  - file_length
  - for_where
  - force_cast
  # - force_try
  - function_body_length
  - function_parameter_count
  # - generic_type_name
  # - identifier_name
  # - implicit_getter
  - inclusive_language
  # - inert_defer
  # - is_disjoint
  # - large_tuple
  # - leading_whitespace ⭕️
  # - legacy_cggeometry_functions ⭕️
  # - legacy_constant ⭕️
  # - legacy_constructor ⭕️
  # - legacy_hashing
  # - legacy_nsgeometry_functions ⭕️
  # - legacy_random
  - line_length
  # - mark ⭕️
  # - multiple_closures_with_trailing_closure
  - nesting
  # - no_fallthrough_only
  # - no_space_in_method_call ⭕️
  - non_optional_string_data_conversion
  - notification_center_detachment
  - nsobject_prefer_isequal
  # - opening_brace ⭕️
  # - operator_whitespace
  # - orphaned_doc_comment
  - private_over_fileprivate
  # - private_unit_test
  - protocol_property_accessors_order
  # - reduce_boolean
  # - redundant_discardable_let ⭕️
  # - redundant_objc_attribute ⭕️
  # - redundant_optional_initialization ⭕️
  # - redundant_set_access_control
  # - redundant_string_enum_value
  # - redundant_void_return ⭕️
  # - return_arrow_whitespace ⭕️
  # - self_in_property_initialization
  # - shorthand_operator
  # - statement_position ⭕️
  # - superfluous_disable_command
  # - switch_case_alignment
  # - syntactic_sugar ⭕️
  - todo
  # - trailing_comma ⭕️
  # - trailing_newline ⭕️
  # - trailing_semicolon ⭕️
  - trailing_whitespace
  - type_body_length
  - type_name
  # - unavailable_condition
  # - unneeded_break_in_switch
  # - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label # ⭕️
  # - unused_enumerated
  # - unused_optional_binding
  # - unused_setter_value
  - valid_ibinspectable
  # - vertical_parameter_alignment
  - vertical_whitespace
  # - void_function_in_ternary
  # - void_return ⭕️
  # - xctfail_message

# 👉🏻 Opt-In Rules
#     주석처리가 되지 않고 작성된 Rule이 적용된 Rule 입니다.
opt_in_rules:
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - raw_value_for_camel_cased_codable_enum
  - return_value_from_void_function
  - sorted_imports
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - weak_delegate
  - yoda_condition

analyzer_rules: # rules run by `swiftlint analyze`
  - explicit_self
  - unused_import

# 👉🏻 lint검사를 하지 않을 Group을 나열합니다.
excluded:
  - Pods
  - SOOUM/Resources
  - SOOUM/Models
  - Pods

# 👉🏻 Options
# line_length: 100

identifier_name:
  min_length: # only min_length
    warning: 0
    error: 0
